print("hello; whats your name ?")
name = input()
print("a wonderful name, whats your age ? " + name)
age = input()
print(name + " whats your country ")
country = input()
print("okay " + name + " i will now collect your data")
print("whats your num ?")
num = input()
print("but wait, whats your gender")
answer = input()
if answer == "male":
    print("okay your boy")
if answer == "female":
    print("okay your girl")
print("collecting data wait....")
print("_________________________________________________________________________________________-")
print("okay now its yur data is hear")
print("name = " + name)
print("age = " + age)
print("country = " + country)
print("num = " + num)
print("gender = " + answer)
print("________________________________")
print("lets play !")
answer = input()
print(name + " , what's the capital of France ?")
if answer == "paris":
print ("yes , you're genuios " + name + " lets continue" )
print("complete the name : Albert Ainech... ")
answer = input ()
if answer == ainchten:
print ("good !")
