print("hello; whats your name ?")
name = input()
print("a wonderful name, whats your age ? " + name)
age = input()
print(name + " whats your country ")
country = input()
print("okay " + name + " i will now collect your data")
print("whats your num ?")
num = input()
print("but wait, whats your gender")
answer = input()
if answer == "male":
    print("okay your boy")
if answer == "female":
    print("okay your girl")
print("collecting data wait....")
print("_________________________________________________________________________________________-")
print("okay now its yur data is hear")
print("name = " + name)
print("age = " + age)
print("country = " + country)
print("num = " + num)
print("gender = " + answer)
